name: Deploy Monitoring Lambda to All Regions

on:
  push:
    paths:
      - lambda-code/monitoring-lambda-code/lambda_function.py
      - lambda-code/monitoring-lambda-code/requirements.txt
      - .github/workflows/deploy-lambdas.yml
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to all Lambda regions
    runs-on: ubuntu-latest

    env:
      FUNCTION_ENV: dev
      REGIONS: ap-south-1 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r lambda-code/monitoring-lambda-code/requirements.txt -t package

      - name: Zip Lambda package for deploying to lambda
        run: |
          cp lambda-code/monitoring-lambda-code/lambda_function.py package/
          cd package
          zip -r ../lambda.zip .

      - name: Deploy Lambda to all regions
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          for region in $REGIONS; do
            function_name="${FUNCTION_ENV}-${region}-lambda-function"
            echo "Deploying to $function_name in $region..."
            aws lambda update-function-code \
              --function-name "$function_name" \
              --zip-file fileb://lambda.zip \
              --region "$region"
          done
