name: Deploy Cognito Code

on:
  push:
    branches:
      - main
    paths:
        - lambda-code/cognito-code/**
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy  Code to Cognito lambda function
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Package lambda code for deployment
        run: |
           echo "Print current directory: $(pwd)"
           ls -la
           WORKSPACE_DIR="$GITHUB_WORKSPACE"
           echo "Workspace directory: $WORKSPACE_DIR"
           ls -la $WORKSPACE_DIR/lambda-code/cognito-code/
           pip install -r $WORKSPACE_DIR/lambda-code/cognito-code/requirements.txt -t $WORKSPACE_DIR/lambda-code/deployment
           cp $WORKSPACE_DIR/lambda-code/cognito-code/lambda_function.py $WORKSPACE_DIR/lambda-code/deployment/
           cd $WORKSPACE_DIR/lambda-code/deployment/
           zip -r $WORKSPACE_DIR/lambda-code/cognito-code.zip .

     